name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.4.1
  firebase_auth: ^4.2.7
  firebase_core: ^2.6.0
  firebase_storage: ^11.0.12
  flutter:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
